### ISSUE TITLE
"str(i), " might not be needed. (or {} might be needed)

### ISSUE THREAD

**Issue by tdrk1980** [cballenar/slideshare-to-pdf#4]
Hi, thank you for sharing an useful script.
During reading your code, I have found a small issue. 
pylint reports "Too many arguments for format string" as below:
![image](https://user-images.githubusercontent.com/6277478/53282580-0d97c280-377d-11e9-951b-10f3abb737b1.png)

So, I think "str(i), " might not be needed for this line(L.122).

**Comment by cballenar** [comment]
Thanks for pointing it out. Yes, that `str(i)` was out of place. It looks like I copied and pasted from a previous line (for shame!). Feel free to submit a pull request next time.

**Comment by cballenar** [comment]
Also, be sure to checkout [SlideGrubber](https://github.com/cballenar/slidegrubber). Can be used as a python package and is more complete. (unless you just need to run as a command line, then you're good).

**Comment by tdrk1980** [comment]
>  Feel free to submit a pull request next time.

OK, I will try it next time. Thank you!

P.S.
This script (with tiny changes) works well on Windows10 / python3.6.
